[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "flet[all]>=0.80.0",
    "httpx>=0.28.1",
    "pip>=25.3",
]
